services:
  app:
    build: .
    container_name: stremioIrProviders
    restart: unless-stopped
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-info}
      DEV_MODE: ${DEV_MODE:-false}
      PORT: 7000
      TMDB_API_KEY: ${TMDB_API_KEY:-}
      F2MEDIA_BASEURL: ${F2MEDIA_BASEURL:-}
      DIGIMOVIE_BASEURL: ${DIGIMOVIE_BASEURL:-}
      DIGIMOVIE_USERNAME: ${DIGIMOVIE_USERNAME:-}
      DIGIMOVIE_PASSWORD: ${DIGIMOVIE_PASSWORD:-}
      PEEPBOXTV_BASEURL: ${PEEPBOXTV_BASEURL:-}
      PEEPBOXTV_USER_ID: ${PEEPBOXTV_USER_ID:-}
      PEEPBOXTV_ANDROID_ID: ${PEEPBOXTV_ANDROID_ID:-}
      PEEPBOXTV_API_KEY: ${PEEPBOXTV_API_KEY:-}
      PROXY_ENABLE: ${PROXY_ENABLE:-false}
      PROXY_URL: ${PROXY_URL:-http://127.0.0.1:3005}
      PROXY_PATH: ${PROXY_PATH:-proxy}
    ports:
      - "7000:7000"

    command: ["pnpm", "start"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:7000/health"]
      interval: 10s
      timeout: 2s
      retries: 2
      start_period: 30s

  proxy:
    build: .
    container_name: stremioIrProviders-proxy
    restart: unless-stopped
    environment:
      PROXY_PORT: 3005
      PROXY_ALLOWED_URLS: ${PROXY_ALLOWED_URLS:-metahub.space,imdb.com,strem.io,tmdb.org}
      PROXY_PATH: ${PROXY_PATH:-proxy}
    ports:
      - "3005:3005"

    command: ["pnpm", "start-proxy"]
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1:3005/health"]
      interval: 10s
      timeout: 2s
      retries: 2
      start_period: 10s
